---
- name: total variable test
  hosts: all
  gather_facts: false
  vars:
    message: "Hello, Ansible"
    hi: "hi ansible"
    hello: "ansible"
    file_path: "/home/ansible/tamp"
  tasks:
  - name: create directory
    file:
      path: "{{ file_path }}"
      state: directory

  - debug:
      msg: "{{ message }}"
  - debug:    
      msg: "{{ hi }}"
  - debug:    
      msg: "{{ hellow }}"